### PR TITLE
Add tests and fix Python3 support

### PR DESCRIPTION
**Pull request by danielquinn**
As per the PR in the Cousteau repo, I'm adding the tests here.  I'm also fixing the use of a print statement that should be a print function.

### CODE REVIEW

**Comment by astrikos** [comment]
I see a lot of commits but a few changes. Is that okay?

**Comment by danielquinn** [comment]
Yeah that was me experimenting with `git pull --rebase` (thank @aabdnn for that one).  I would do a pull from upstream and then a pull from my repo and it'd complain at me, so I turned off the automatic rebase and this happened.

As far as I can tell, there's no actual problem as the files are only changed in the way you see here.  It's probably just a commit ordering thing.

**Comment by astrikos** [comment]
No, then I think it's not good! we might overwrite commits that are public, so other people might have problems. Check for example commit with text "A simple sanitiser", in your branch it has id af7e8f1 but on master is 7cf8989, so I think if we merge we will end up with either with duplicates commits or rewriting public history. Could you make a new branch from NCC'S master and then cherry-pick your change only?

**Comment by danielquinn** [comment]
From my local, I just did a `git pull upstream master` and it claimed that nothing was changed.  Should I run some sort of `reset` or something?  I'm afraid I have no idea when it comes to git innards like this.

**Comment by astrikos** [comment]
Since I am not sure about your local, what I would do is delete the fork and create an new one that will be clean and in sync with master. Do you have a lot of changes that you are going to loose if you delete tour fork?

**Comment by danielquinn** [comment]
Nope, it's just this one.  I'll do that.

**Comment by danielquinn** [comment]
Nothing a `git pull --rebase upstream master && git push -f` can't fix ;-)

**Comment by astrikos** [comment]
Cool

**Pull request merged**
