### PR TITLE
IP cache tests improvement

### PR DESCRIPTION
**Pull request by pierky**

### CODE REVIEW

**Comment by astrikos** [comment]
I think inside the file like you have it is good enough. I would only move it to it's own dict with a name that makes clear it's for mocking data (e.g RIPEstatMockResults). And definitely pep8 it :) I like 100 loc limit, but today @danielquinn  convinced(?) me to use 80, so let's go full pep8!

**Comment by danielquinn** [comment]
@astrikos is going to hate me for this, but I have no problem with exceeding the 80character limit in tests.  The alternative is 100+ lines of data we don't actually need to read, so no, what @pierky has done here is just fine by me.

...with three exceptions:

### CamelCase

You've got camelCase all over the place there.  That's very unpythonic as pep8 does call for the use of underscores unless we're specifically talking about a class name.

### A Single Constant

Your class has one constant:

    RIPESTAT_REQ = {
        'IP': '193.0.6.1',
        'ASN': '3333',
        'SamePrefixIP': '193.0.6.2',
        'SameASDifferentPrefixIP': '193.0.22.1',
        'NotAnnouncedIP': '80.81.192.1',
        'RIPEstatResults': {
            '193.0.6.1': 'stuff',
            '193.0.22.1': 'stuff',
            '80.81.192.1': 'stuff'
        }
    }
 
But from what I can tell, you're using all of the elements of that dictionary in different places and no where do you use it as a whole.  In this case, it makes much more sense to construct your class like this:

    IP = "193.0.6.1"
    ASN = "3333"
    SAME_PREFIX_IP = "193.0.6.2"
    SAME_AS_DIFFERENT_PREFIX_IP = "193.0.22.1"
    NOT_ANNOUNCED_IP = "80.81.192.1"
    RESULTS = {
        IP: "stuff",
        SAME_PREFIX_IP: "stuff",
        NOT_ANNOUNCED_IP: "stuff"
    }

### Lack of Self

You've got a bunch of lines like this:

    TestIPDetails.RIPESTAT_REQ["IP"]

In all of these cases, you have access to `self`, so you should probably be using that.  In combination with the above, bit about a single constant, you can reduce this to:

    self.IP

**Comment by danielquinn** [comment]
An alternative to storing the test data in these very long lines would be to keep it in a separate test data file or something.  If we want to be rigid on pep8, then this would be an option. @astrikos?  What say you?

Example code:

```python
def get_test_data(line_number):
    with open(MyTestClass.DATA_FILE) as f:
        return f.readlines()[line_number].strip()


class MyTestClass(unittest.TestCase):
    DATA_FILE = "/path/to/data.txt"
    RESULTS = {
        IP: get_test_data(0),
        SAME_PREFIX_IP: get_test_data(1),
        NOT_ANNOUNCED_IP: get_test_data(2)
    }
```

...but this feels like an awful long way to go for pep8, and it effectively obfuscates the nature of the test.

**Comment by astrikos** [comment]
I say it would be nice as future optimisation :) make this structure pep8 takes around 170locs so it's not that bad. Let's keep it in this file for now and if at some point it becomes huge we can deal with it. Over-engineering might kill us (note to myself as well :))

**Comment by pierky** [comment]
@danielquinn, @astrikos, thanks for all your feedbacks on this.

# To cache or not to cache

> So, TL;DR and in answer to your question, I don't recommend any type of caching for unit tests, because unit tests need to test units and not external services.

As @astrikos pointed out, I used misleading words to describe what I did in my previous PR; I meant to store RIPEstat results within the Python code (as I did) and use them to test the IP cache class.
I was also considering to add only one test to verify RIPEstat reachability and output format, but finally @danielquinn convinced me to avoid this. At this time there are no external dependencies nor RIPEstat real time calls in the test unit.

# RIPEstat results

Even if I was not convinced about the inclusion of RIPEstat results within the code, I prefer to keep them on a single loc for the sake of readibility of the rest of code.
The idea of a separate class/file is good, but :+1: to no over-engineering it :)

# Style

Sorry for my poor python-ness, I'll try to do better in the future!
I (obviously) adopted all your suggestions (`setUp` to configure mock, I chased the camel and found my`self` again).

**Pull request merged**
