### PR TITLE
Python3 has mock built into unittest

### PR DESCRIPTION
**Pull request by danielquinn**
In Python3, `import mock` explodes since it's now part of the `unittest` standard library.

### CODE REVIEW

**Comment by astrikos** [comment]
I don't think it explodes...
```code
Python 3.4.3 (v3.4.3:9b73f1c3e601, Feb 23 2015, 02:52:03)
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import mock
>>> from unittest import mock
```

As stated on [PyPi](https://pypi.python.org/pypi/mock/1.3.0) mock is a `Rolling backport of unittest.mock for all Pythons`. Since we already install it through test_requires we have it for all pythons. 
What would make more sense if we want to go that way is skip installing it under py3 and have this try-catch clauses wherever we import it.
But maybe is too much pain and ugliness of code in that stage...

**Comment by danielquinn** [comment]
Sorry, I meant to say that on Python 3, "import mock" explodes if mock isn't already installed.  I didn't actually see this project explode on Python 3.  I ran into this when I copy/pasted some code from this file into a new project to get a start for writing tests and it exploded locally (we don't support Python 2.x).

I think that coding it this way is a good practise regardless since it defaults to Python 3, but you've got a point that if we're requiring the installation of mock regardless, it's sort of a moot point.

I leave it to you to merge or not.  It won't hurt my feelings if you reject it ;-)

**Comment by astrikos** [comment]
@danielquinn sorry for long delay, I am okay with going that way as long as we do it everywhere. Fixing it only in one place it will be confusing after some time. If you have some time some day you could change rest of the stuff and then we merge it. Sounds good?

**Comment by danielquinn** [comment]
Sure.  Just leave this PR open and I'll try to get to that this week.

**Comment by astrikos** [comment]
hm not sure why that failed! complains it cannot find cousteau. should i try to merge? i think it seems good. maybe travis had a problem at that time.

**Comment by danielquinn** [comment]
Yeah it was pretty weird.  I couldn't reproduce the problem from my end so I have to assume it's a quirk of PyPi maybe.  So long as this isn't something that's likely to happen again, I'll do boring commit and see if I can get Travis to trigger the checks again.

**Comment by astrikos** [comment]
okay it seems happy now. merging. Thanks @danielquinn :)

**Pull request merged**
