### PR TITLE
A method to pass options to renderers

### LINKED ISSUE #155: traceroute_aspath renderer does not show all AS
ripe-atlas report 3606560 --renderer traceroute_aspath
Probe #12185:  AS10026   AS1921, completed
Probe #22880:  AS10026   AS1921, completed

This is not complete. The traceroute shows:
1 192.168.2.254
2 96.120.89.13
3 68.87.198.29
4 162.151.79.133
5 68.85.154.93
6 4.68.127.109
7 4.69.144.143
8 4.69.144.143
9 64.215.81.146
10 202.147.51.46
11 194.0.25.10

Those the AS path should be something like:
?, 7922, 3356, 3549, 10026, 1921

It would also be great if the renderer could write down the AS name (I know this is probably more difficult)

### PR DESCRIPTION
**Pull request by pierky**
In order to allow Renderers to add their own custom arguments to the main `argparse` and to receive optional user-provided parameters I've introduced a new method, `add_arguments()`. Everywhere the `--renderer` argument is provided the `Renderer.add_arguments_for_available_renderers()` method is called too: it cycles through all the `Renderer` classes and calls their `add_arguments()` method.
When the renderer is instantiated its `__init__()` is provided with the full `argparse.parse_args()` results, so that it can read its own optional arguments.
This new internal feature can be used to fix #155 for example (see the `--traceroute-aspath-radius` argument).

### CODE REVIEW

**Comment by astrikos** [comment]
@pierky , sorry it took that long for response. Adding renderer specific arguments seems nice addition, and the way you implemented it is also good. The only thing i miss is a simple test that will make sure the additional argument is respected and used if it's passed. You made some core changes so, it's good if they are covered by tests as well. Since it's now used only for traceroute as-path renderer could you write a small test to check if radius argument is respected if someone uses it.

**Comment by pierky** [comment]
@astrikos Sure, just added some tests.

**Comment by astrikos** [comment]
@pierky excellent. Only now I see it's conflicting. Most likely @danielquinn mock changes are conflicting with your changes. I cannot merge if you don't resolve. Can you pull all recent changes from master and merge them back to your branch and resolve the issues? I think it should be easy enough.

**Comment by pierky** [comment]
@astrikos it should be OK now.

**Comment by astrikos** [comment]
cool, merging!

**Pull request merged**
